# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba67e5175e3a0f9241923dfbeb327282b76a8e9d638a4c088ff1f9fada94a255e202e604491486b43b54d52e3a7e05306735882531ab4a92e33b0bc2c7fbeeba

test:
  secret_key_base: 80b98ca01f082e57e0a2fc47ff356662dc4f12610b9a3c95000aaf63f7684c83194bfa4d62f4ae23fd7cf1a2c424b5b6bae543eae7395ccb832a7324ad7b51b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
